---
title: "Random Effects"
format: html
editor: visual
---

## Loading packges

```{r}
#| warning: false
#| echo: false
#| include: false

rm(list = ls());gc()
pacman::p_unload(pacman::p_loaded(), character.only = TRUE)

library(lme4)
library(ggplot2)

```

## Strong individual effects

对于第一个例子，我生成了一些数据，其中我想象在五个不同水平的治疗（固定效应）下测量了相同的九个人（随机效应）。在第一组数据中，我包括了强烈的个体效应。以下是数据图：

```{r}
#create some levels
levs <- as.factor(c("l1","l2","l3","l4","l5"))
#set the factor means
f_means <- c(6,16,2,10,13)
# set individual as a factor
ind <- as.factor(paste("i",1:9,sep=""))
#Set individual effects
i_eff <- seq(-4,4,length=9)
#now let's simulate a repeated measure for each individuals
idf <- data.frame(matrix(0,ncol=3,nrow=45))
colnames(idf) <- c("size","ind","levs")
counter <- 1
for(i in 1:length(levs)){
  for(j in 1:length(ind)){
    idf$size[counter] <- rnorm(1,f_means[i]+i_eff[j],.3)
    idf$ind[counter] <- ind[j] 
    idf$levs[counter] <- levs[i]
    counter <- counter + 1
  }
}
idf$ind <- rep(ind,5)
idf$levs <- sort(rep(levs,9))

ggplot(idf,aes(x=levs,y=size,group=ind,colour=ind))+geom_point()+geom_path()
```

```{r}
m1 <- lmer(size ~ levs - 1 + (1 | ind), data = idf)
reduced.lmer <- lmer(size ~ 1 + (1 | ind), data = idf)
summary(m1)
```

```{r}
anova(reduced.lmer, m1)
```

```{r}
m2 <- aov(size ~ levs-1, data = idf)
summary(m2)
```

```{r}
AIC(m1, m2)
```

```{r}
## Now let's randomize the individuals
idf_rand <- idf
for(i in 1:5){
  idf_rand$ind[idf_rand$levs==levs[i]]  <- sample(idf$ind[idf$levs==levs[i]],9,replace=F)
  
}

# here we can visualize the data and examine individual effects
ggplot(idf_rand,aes(x=levs,y=size,group=ind,colour=ind))+geom_point()+geom_path()

```

```{r}
m3 <- lmer(size ~ levs - 1 + (1 | ind), data = idf_rand)
m4 <- aov(size ~ levs - 1, data = idf_rand)
summary(m3)
```

```{r}
AIC(m3, m4)
```
